name: CI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: self-hosted
    steps:
     - name: Check out the repo
       uses: actions/checkout@v2
     - name: Set Relase version
       id: vars
       run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
     - name: build docker image and push to ecr repo
       run: |
          sudo docker build -t ${{ secrets.ECR_REPO_NAME }}/ismaeel-test-repo:latest .
          $(aws ecr get-login --no-include-email --region us-east-2)
          sudo docker push ${{ secrets.ECR_REPO_NAME }}/ismaeel-test-repo:latest
       env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          
     - name: Check tag version
       run: | 
           echo $RELEASE_VERSION
           echo ${{ env.RELEASE_VERSION }}
           echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
           echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
     - name: terraform initialization 
       run: cd devops/ && terraform init 
     - name: terraform deployment
       run: cd devops/ && terraform apply -var="tag=latest}"  -auto-approve

     
